version: '3'
networks:
    fcdnet:
        driver: 'bridge'

services: 
    node:
        build: 
            context: ./node
        container_name: node
        volumes: 
            - ./node:/usr/src/app
        networks: 
            - fcdnet
        depends_on: 
            - db
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
        
    nginx:
        build: 
            context: ./nginx
        container_name: nginx
        ports: 
            - "8080:80"
        networks: 
            - fcdnet
        depends_on: 
            - node
    
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - fcdnet

